import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import ToastProvider from '@/contexts/toast';
import AuthProvider from '@/contexts/auth';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const myFont = localFont({
  src: [
    {
      path: '../../public/fonts/NanumSquareNeoOTF-Rg.otf',
      weight: '400',
    },
    {
      path: '../../public/fonts/NanumSquareNeoOTF-Eb.otf',
      weight: '700',
    },
    {
      path: '../../public/fonts/NanumSquareNeoOTF-Hv.otf',
      weight: '900',
    },
  ],
  display: 'swap',
});

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ko">
      <body className={`${myFont.className}`}>
        <ToastProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
