name: Deployment

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0
      -
        name: Build and push
        uses: docker/build-push-action@v6.15.0
        with:
          push: true
          tags: |
            henoziwd/opqo:latest
            henoziwd/opqo:${{ github.event.release.tag_name }}
          build-args: |
            NEXT_PUBLIC_CDN_HOSTNAME=${{ secrets.NEXT_PUBLIC_CDN_HOSTNAME }}
            NEXT_PUBLIC_SERVER_URL=${{ secrets.NEXT_PUBLIC_SERVER_URL }}
            NEXT_PUBLIC_CDN_CHANNELIMAGE_URL=${{ secrets.NEXT_PUBLIC_CDN_CHANNELIMAGE_URL }}
            NEXT_PUBLIC_CDN_VIDEO_URL=${{ secrets.NEXT_PUBLIC_CDN_VIDEO_URL }}
            NEXT_PUBLIC_CDN_THUMBNAIL_URL=${{ secrets.NEXT_PUBLIC_CDN_THUMBNAIL_URL }}
      -
        name: Add SSH key to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      -
        name: Deploy to EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_SSH_KEY" > opqo_aws_action.pem
          chmod 400 opqo_aws_action.pem

          ssh -i opqo_aws_action.pem ubuntu@${{ secrets.EC2_HOST }} << EOF
          
            cd /home/ubuntu
            docker compose down
            docker compose pull
            docker compose up -d
          EOF

          rm -f ec2_key.pem
